services:
  - type: web
    name: trpc-nextjs-starter
    env: node
    plan: free
    buildCommand: yarn --prod=false &&
      yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthz
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: trpc-nextjs-starter-db
          property: connectionString

      - fromGroup: trpc-nextjs-starter

databases:
  - name: trpc-nextjs-starter-db
    plan: free
